<?php
	session_start();
    
    $host = "303.itpwebdev.com";
    $user = "bglascoc_db_user";
    $password = "mydbpassword";
    $db = "bglascoc_puzzle_db";

    $mysqli = new mysqli($host, $user, $password, $db);
    if($mysqli->connect_errno)
    {
        echo $mysqli->connect_error;
        exit();
    }

    $sql = "SELECT * FROM comments
    JOIN users ON comments.user_id = users.user_id
    JOIN puzzles ON comments.puzzle_id = puzzles.puzzle_id
    WHERE puzzles.puzzle_id = 2
    ORDER BY comment_id DESC;";

    $results = $mysqli->query($sql);
    if ($results == false)
    {
        echo $mysqli->error;
        exit();
    }

    $mysqli->close();
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="quest.css">
    <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Goldman&display=swap" rel="stylesheet">
    <style>
		#nav-puzzle2
		{
			color: #00aeff !important;
		}
	</style>
    <title>Puzzle 2</title>
</head>
<body onload="addSubmitOnEnter('answer', 'submit-answer');">
    <?php include 'nav.php'; ?>

    <div class="jumbotron">
		<h1 class="display-4">Puzzle 2</h1>
    </div>

    <div class="container">
		<div class="row">
			<div class="col col-12">
                <div class="h1">Puzzle 2:</div>
                <div>We were snooping through our target's office when we found this sticky note on his monitor. We believe it's a hint to his password. However, his computer's login screen has a bizarre encryption system. Solve the riddle and figure out how to input the answer, and hurry!</div>
                <br>
            </div>
            <div class="col col-12">
                <div id="riddle">
                When I'm young, I'm tall<br>
                When I'm old, I'm short<br>
                When I'm alive, I glow<br>
                Because of your breath, I die<br><br>
                What am I?
                </div>
                <br>
                <div id="answer-form">
                    <div class="form-group row">
                        <div class="col-6 col-md-3">
                            <label for="answer">Input:</label>
                            <input type="text" class="form-control" maxlength="6" id="answer" placeholder="Enter answer">
                        </div>
                    </div>
                    <div class="mb-3" id="output">Output: </div>
                    <button id="submit-answer" class="btn btn-color btn-primary mb-2">Submit</button>
                    <div class="mb-2" id="correct-msg"></div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col col-12" id="hint-section">
                <div class="h2">Hints:</div>
                <div class="h5">Hint 1 ▼</div>
                <p class="hide">The riddle is describing an object you might use at a birthday party.</p>
                <div class="h5">Hint 2 ▼</div>
                <p class="hide">Once you know the answer to the riddle, your goal is to make it appear in the "output" box.</p>
                <div class="h5">Hint 3 ▼</div>
                <p class="hide">The output is generated by simply converting your input and the existing output to numbers (A=1, B=2, etc.) and adding them, wrapping back around to A if the sum exceeds 26.</p>
            </div>
        </div>

        <div class="row">
            <div class="col col-12 mb-3" id="comment-section">
                <div class="h2">Comments</div>
                <div id="no-comments"><?php if($results->num_rows == 0){echo "No comments yet.";}?></div>
                <?php while($row = $results->fetch_assoc()) : ?>
                    <div id="comment-<?php echo $row['comment_id'];?>" class="comment"><strong><?php echo $row['username'];?></strong> says: <span id="comment-text-<?php echo $row['comment_id'];?>"><?php echo $row['comment'];?></span>
                        <?php if(isset($_SESSION["logged_in"]) && $_SESSION["logged_in"] && $row['user_id'] == $_SESSION['user_id']) : ?>
                            <a class="show-form" onclick="showForm(<?php echo $row['comment_id'];?>);"><u>(Edit/Delete)</u></a>
                        <?php endif; ?>
                    </div>
                    <?php if(isset($_SESSION["logged_in"]) && $_SESSION["logged_in"] && $row['user_id'] == $_SESSION['user_id']) : ?>
                        <div class="row">
                            <form class="edit-form col-11 col-md-8 col-lg-6 ml-4 mt-2 mb-2" id="edit-form-<?php echo $row['comment_id'];?>">
                                <div class="form-group">
                                    <div class="text-danger" id="error-<?php echo $row['comment_id'];?>"></div>
                                    <label for="edit-<?php echo $row['comment_id'];?>" class="h6">Edit comment:</label>
                                    <input type="text" class="form-control" id="edit-<?php echo $row['comment_id'];?>" value="<?php echo $row['comment'];?>">
                                </div>
                                <button type="submit" id="submit-edit-<?php echo $row['comment_id'];?>" class="btn btn-color btn-primary mr-1" onclick="editComment(<?php echo $row['comment_id'];?>);">Edit</button>
                                <button type="button" id="delete-comment-<?php echo $row['comment_id'];?>" class="btn btn-danger mr-1" onclick="deleteComment(<?php echo $row['comment_id'];?>);">Delete</button>
                                <button type="button" id="cancel-form-<?php echo $row['comment_id'];?>" class="btn btn-secondary" onclick="hideForm(<?php echo $row['comment_id'];?>);">Cancel</button>
                            </form>
                        </div>
                    <?php endif; ?>
                <?php endwhile;?>
            </div>
            <?php if(isset($_SESSION["logged_in"]) && $_SESSION["logged_in"]) : ?>
                <div class="col col-12">
                    <form id="comment-form" onsubmit="postComment()">
                        <div class="form-group row">
                            <div class="col-6 col-md-3">
                                <label for="comment" class="h6">Add a comment:</label>
                                <input type="text" class="form-control" id="comment" placeholder="Your comment" required>
                                <input type="number" value="2" id="puzzle-id-hidden">
                                <input type="number" value="<?php echo $_SESSION["user_id"];?>" id="user-id-hidden">
                                <input type="text" value="<?php echo $_SESSION["username"];?>" id="username-hidden">
                            </div>
                        </div>
                        <button type="submit" id="post-comment" class="btn btn-color btn-primary">Post</button>
                    </form>
                </div>
            <?php endif;?>
        </div>

        <div class="row">
			<div id="footer">
				<div class="col col-12">
					<hr class="solid" style="border-color:white">
					<div>© 2020 Brendan Glascock</div>
				</div>
			</div>
        </div>

    </div>
    <script type="text/javascript" src="./puzzle2.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>